### PR TITLE
.env exposed ( CRITICAL )

### PR DESCRIPTION
**Pull request by Shub3am**
.env got exposed and it may cause serious vulnerabilities, added env file to gitignore to automatically ignore it in future

### CODE REVIEW

**Comment by Shub3am** [comment]
we should also have a exampleENV text file or mention it in ReadMe file for env prerequisites

**Comment by Shub3am** [comment]
hey maintainer, can you add hacktoberfest label to this pr, Thank You

**Comment by Shub3am** [comment]
@shanmukh-sai2003 any updates on this

**Comment by mshreeram** [comment]
@Shub3am  Hey Thanks for your interest in contributing,
But we intentionally left the .env file exposed ,
since we are now operating in development phase we thought that it would be easier for working this way,
btw, the database endpoint exposed in the file is just a test db, 
we will definitely change the configurations while going to prod.

**Pull request closed without merging**
